// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Example struct {
	ID          int32            `db:"id" json:"id"`
	UserID      int32            `db:"user_id" json:"user_id"`
	Title       string           `db:"title" json:"title"`
	Description pgtype.Text      `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type RefreshToken struct {
	ID        int32            `db:"id" json:"id"`
	UserID    int32            `db:"user_id" json:"user_id"`
	Token     string           `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	IsRevoked pgtype.Bool      `db:"is_revoked" json:"is_revoked"`
}

type Upload struct {
	ID               int32            `db:"id" json:"id"`
	UserID           int32            `db:"user_id" json:"user_id"`
	FolderID         int32            `db:"folder_id" json:"folder_id"`
	Type             string           `db:"type" json:"type"`
	RelativePath     string           `db:"relative_path" json:"relative_path"`
	OriginalFilename string           `db:"original_filename" json:"original_filename"`
	FileSize         int64            `db:"file_size" json:"file_size"`
	MimeType         pgtype.Text      `db:"mime_type" json:"mime_type"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID              int32            `db:"id" json:"id"`
	Email           string           `db:"email" json:"email"`
	Name            string           `db:"name" json:"name"`
	Password        string           `db:"password" json:"password"`
	Roles           []string         `db:"roles" json:"roles"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	EmailVerifiedAt pgtype.Timestamp `db:"email_verified_at" json:"email_verified_at"`
}
